### ISSUE TITLE
Reference name generation based on filename including uppercase characters

### ISSUE THREAD

**Issue by serens** [PeterSonne/gulp-fscss#1]
Hi there,
1st of all, thank you for providing this plugin!

I found following behavior: Given a filename "Materialicons-regular.ttf" results in a reference name "_aterialicons_regular_ttf".

This happens in `.replace(/[^a-z0-9_]+/g, '_')` which should support A-Z as well or include the "i" flag. Afterwards, the filename should be changed to lower case:

```
const fileBasename = match[3]
                    .split('/')
                    .pop()
                    .split('.')
                    .shift()
                    .replace(/[^a-z0-9_]+/gi, '_')
                    .toLowerCase();
```

Regards, Sven

**Comment by PeterSonne** [comment]
Hi Sven - and first of all thanks for contributing and sorry for the delay!

Just to understand you right:
`Materialicons-regular.ttf` should be turned into `materialicons_regular_ttf`, right?
So wouldn't it make sense to convert to lowercase first, and then do the regex? (Just asking so I don't have it wrong in my mind).

**Comment by serens** [comment]
Hi Peter,
no problem! :)

Yes, you are correct. Doing the `.toLowerCase()` first would solve the problem as well.

Regards, Sven

**Comment by PeterSonne** [comment]
Ah, perfect - so I was on the right track.
Looks great, I'd say it's your honor to increase the package version to 1.0.5 then ;)
